[metadata]
name         = "pnpm-scripts"
description  = "Run pnpm scripts from root package.json"
requirements = ["pnpm", "jq"]

[source]
ansi   = true
output = "{strip_ansi|split: :0}"

  [[source.command]]
  name = " Scripts"
  run  = """
  cat $(git rev-parse --show-toplevel)/package.json |
  jq -r '.scripts | to_entries[] | ["\\u001b[34m\\(.key)\\u001b[0m", "\\u001b[37m\\(.value)\\u001b[0m"] | @tsv' |
  column -t -s (printf '\t')
  """

[ui]
layout = "landscape"

  [ui.input_bar]
  position = "top"
  prompt   = "  "

  [ui.preview_panel]
  header    = " {strip_ansi|split: :0}"
  footer    = "⌃ + o: Open browser | ⌃ + y: yank URL"
  scrollbar = true

[preview]
command = "echo 'pnpm run {strip_ansi|split: :0}'"

[keybindings]
enter = "actions:run"

[actions.run]
description = "Run the selected pnpm script"
command     = "pnpm run {strip_ansi|split: :0}"
mode        = "execute"
