# -*-mode:toml-*- vim:ft=toml
# Reference: https://github.com/JohnnyMorganz/StyLua#configuration

column_width = 120
line_endings = "Unix"
indent_type  = "Spaces"
indent_width = 2
quote_style  = "AutoPreferDouble"
no_call_parentheses = true

[sort_requires]
enable = false
