default: true

MD007:
  indent: 2
MD004: false # Unordered list style
MD010: false # Hard tabs
MD012: false # no-multiple-blanks - Multiple consecutive blank lines
MD013: false # line-length - Line length
MD024: false # no-duplicate-heading/no-duplicate-header - Multiple headings with the same content
MD033: false # no-inline-html - Inline HTML
MD041: false # first-line-heading/first-line-h1 - First line in a file should be a top-level heading
MD045: false # Images should have alternate text (alt text)
