# -*-mode:gitconfig-*- vim:ft=gitconfig

[interactive]
  diffFilter = delta --color-only --24-bit-color

[delta]
  features     = side-by-side line-numbers decorations
  syntax-theme = Monokai Extended
  side-by-side = true
