[ai.mcp.servers.filesystem]
type = "local"
cmd  = ["pnpm", "dlx", "@modelcontextprotocol/server-filesystem@latest"]

[ai.mcp.servers.memory]
type = "local"
cmd  = ["pnpm", "dlx", "@modelcontextprotocol/server-memory@latest"]

[ai.mcp.servers.sequential-thinking]
type = "local"
cmd  = ["pnpm", "dlx", "@modelcontextprotocol/server-git@latest"]

[ai.mcp.servers.time]
type = "local"
cmd  = ["uvx", "mcp-server-time"]

[ai.mcp.servers.fetch]
type = "local"
cmd  = ["uvx", "mcp-server-fetch"]

[ai.mcp.servers.git]
type = "local"
cmd  = ["uvx", "mcp-server-git"]

[ai.mcp.servers.context7]
type = "remote"
url  = "https://mcp.contexty.com/mcp"

[ai.mcp.servers.context7.headers]
CONTEXT7_API_KEY = "${CONTEXT_API_KEY}"

[ai.mcp.servers.grep_app]
type = "remote"
url  = "https://mcp.grep.app"
