################################################################################
# OpenCode Zen
################################################################################
[ai.providers.opencode]
name    = "OpenCode Zen"
api     = "openai-completions"
npm     = "@ai-sdk/openai-compatible"
baseUrl = "https:/opencode.ai/zen/v1"
apiKey  = "$OPENCODE_API_KEY"

  [[ai.providers.opencode.models]]
  id            = "deepseek-v4-flash-free"
  name          = "DeepSeek V4 Flash"
  reasoning     = true
  input         = ["text"]
  contextWindow = 200000
  maxTokens     = 128000

  [[ai.providers.opencode.models]]
  id            = "mimo-v2.5-free"
  name          = "Mimo v2.5"
  reasoning     = true
  input         = ["text"]
  contextWindow = 1048576
  maxTokens     = 131072

  [[ai.providers.opencode.models]]
  id            = "nemotron-3-ultra-free"
  name          = "NVIDIA Nemotron 3 Ultra"
  reasoning     = true
  input         = ["text"]
  contextWindow = 1000000
  maxTokens     = 128000

  [[ai.providers.opencode.models]]
  id            = "north-mini-code-free"
  name          = "North Mini Code"
  reasoning     = true
  input         = ["text"]
  contextWindow = 256000
  maxTokens     = 64000

  [[ai.providers.opencode.models]]
  id            = "big-pickle"
  name          = "Big Pickle"
  reasoning     = true
  input         = ["text"]
  contextWindow = 200000
  maxTokens     = 32000

################################################################################
# Openrouter
################################################################################
[ai.providers.openrouter]
name    = "OpenRouter"
api     = "openai-completions"
npm     = "@ai-sdk/openai-compatible"
baseUrl = "https:/openrouter.ai/api/v1"
apiKey  = "$OPENROUTER_API_KEY"

  [[ai.providers.openrouter.models]]
  id   = "nvidia/nemotron-3-ultra-550b-a55b:free"
  name = "NVIDIA Nemotron 3 Ultra"

  [[ai.providers.openrouter.models]]
  id   = "nvidia/nemotron-3-super-120b-a12b"
  name = "NVIDIA Nemotron 3 Super"

################################################################################
# Ollama Cloud
################################################################################
[ai.providers.ollama]
name    = "Ollama Cloud"
api     = "openai-completions"
npm     = "@ai-sdk/openai-compatible"
baseUrl = "https:/ollama.com/v1"
apiKey  = "$OPENROUTER_API_KEY"

  [[ai.providers.ollama.models]]
  id            = "glm-5.2:cloud"
  name          = "GLM 5.2"
  reasoning     = true
  contextWindow = 1000000
  maxTokens     = 131072

  [[ai.providers.ollama.models]]
  id            = "kimi-k2.7-code:cloud"
  name          = "Kimi K2.7 Code"
  reasoning     = true
  contextWindow = 262144
  maxTokens     = 65536

  [[ai.providers.ollama.models]]
  id            = "glm-5.1:cloud"
  name          = "GLM 5.1"
  reasoning     = true
  contextWindow = 202752
  maxTokens     = 131072

  [[ai.providers.ollama.models]]
  id            = "kimi-k2.6:cloud"
  name          = "Kimi k2.6"
  reasoning     = true
  contextWindow = 262144
  maxTokens     = 32768

  [[ai.providers.ollama.models]]
  id            = "minimax-m3:cloud"
  name          = "MiniMax m3"
  reasoning     = true
  contextWindow = 1024000
  maxTokens     = 131072

  [[ai.providers.ollama.models]]
  id   = "nemotron-3-ultra:cloud"
  name = "NVIDIA Nemotron 3 Ultra"

################################################################################
# HuggingFace
################################################################################
[ai.providers.huggingface]
name    = "Ollama Cloud"
api     = "openai-completions"
npm     = "@ai-sdk/openai-compatible"
baseUrl = "https:/router.huggingface.co/v1"
apiKey  = "$HUGGINGFACE_TOKEN"

  [[ai.providers.huggingface.models]]
  id            = "deepseek-ai/deepseek-v4-pro"
  name          = "DeepSeek-V4-Pro"
  reasoning     = true
  input         = ["text"]
  contextWindow = 1048576
  maxTokens     = 393216

  [[ai.providers.huggingface.models]]
  id            = "moonshotai/kimi-k2.6"
  name          = "Kimi k2.6"
  reasoning     = true
  input         = ["text", "image"]
  contextWindow = 262144
  maxTokens     = 262144

  [[ai.providers.huggingface.models]]
  id            = "minimaxai/minimax-m2.7"
  name          = "MiniMax m2.7"
  reasoning     = true
  input         = ["text"]
  contextWindow = 204800
  maxTokens     = 131072

  [[ai.providers.huggingface.models]]
  id            = "zai-org/glm-5.1"
  name          = "GLM-5.1"
  reasoning     = true
  input         = ["text"]
  contextWindow = 202752
  maxTokens     = 131072

  [[ai.providers.huggingface.models]]
  id            = "zai-org/glm-5"
  name          = "GLM-5"
  reasoning     = true
  input         = ["text"]
  contextWindow = 202752
  maxTokens     = 131072
