# -*-mode:conf-toml-*- vim:ft=toml

[font.family]
    ascii    = "JetBrainsMonoNL Nerd Font Mono"
    nonascii = "HackGen Console NF"

[font.size]
    large  = 14
    medium = 12
    small  = 10

[alacritty]
    theme = "dracula"
    opacity = 0.75

[asdf.version]
    node   = "20.8.0"
    pnpm   = "8.8.0"
    deno   = "1.37.1"
    bun    = "1.0.3"
    python = "3.11.5"
    poetry = "1.6.1"
    ruby   = "3.2.2"
