# -*-mode:conf-toml-*- vim:ft=toml

[font.family]
    ascii    = "JetBrainsMonoNL Nerd Font Mono"
    nonascii = "HackGen35 Console NF"

[font.size]
    large  = 14
    medium = 12
    small  = 10

[alacritty]
    theme = "dracula"
    opacity = 0.75
