# -*-mode:toml-*- vim:ft=toml

[".local/share/tmux/plugins/tpm"]
    type = "git-repo"
    url = "https://github.com/tmux-plugins/tpm"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"

[".local/share/alacritty/themes"]
    type = "git-repo"
    url = "https://github.com/alacritty/alacritty-theme"
    exact = true
    refreshPeriod = "168h"
