# -*-mode:conf-toml-*- vim:ft=toml

[font.family]
ascii    = "JetBrainsMonoNL NFM"
nonascii = "HackGen Console NF"
combined = "UDEV Gothic NFLG"

[font.size]
xlarge = 16
large  = 14
medium = 12
small  = 10
xsmall = 8

[alacritty]
theme = "dracula"
opacity = 0.75

[wezterm]
themes = [
  "Spring (Gogh)",
  "ThayerBright (Gogh)",
  "TokyoNightStorm (Gogh)",
]
images = [
  "daft-punk-music-retro-style-wallpaper.jpg",
  "daft-punk-music-black-background-helmet-wallpaper.jpg",
  "daft-punk-punk-edm-music-wallpaper.jpg",
]

[starship.env]
fg_color = "#7aa2f7"
bg_color = "#242529"

[starship.path]
fg_color = "#69f9c3"
ro_color = "#f7768e"

[starship.git.status]
ahead      = "#ddffa7"
behind     = "#ff8b92"
untracked  = "#a88847"
conflicted = "#ff8b6b"
stashed    = "#24ffa0"
modified   = "#da6633"
staged     = "#f2d166"
renamed    = "#6495ed"
deleted    = "#c00000"
up_to_date = "#adff2f"

[starship.git.metrics]
added   = "#00aa64"
deleted = "#ea5ea8"

[starship.git.branch]
fg_color = "#090c09"
bg_color = "#a2b1c1"

[starship.clock]
fg_color = "#300906"
bg_color = "#9c9cff"

[starship.cmd]
color = "#3399ff"

[neovim.plugins]
chatgpt = true
copilot = true

[mise.node]
enabled  = true
versions = ["20"]

[mise.pnpm]
enabled  = true
versions = ["latest"]

[mise.deno]
enabled  = true
versions = ["1"]

[mise.bun]
enabled  = false
versions = ["1"]

[mise.go]
enabled  = true
versions = ["latest"]

[mise.python]
enabled  = true
versions = ["3.11", "3.12"]

[mise.ruby]
enabled  = true
versions = ["3.3"]

[packages]
npm = [
  "neovim",
  "create-{react,next}-app",
  "commitizen",
  "cz-conventional-changelog",
]
go  = [
]
python = [
  "pynvim",
]
gem = [
  "bundler",
  "neovim",
]

[plugins]
gh = [
  "dlvhdr/gh-dash",           # Dashboard
  "actions/gh-actions-cache", # Manage GitHub Actions cache
  "kawarimidoll/gh-graph",    # Activity graph
  "meiji163/gh-notify",       # Notification Extension
  "gennaro-tedesco/gh-s",     # Search respositories interactively
]
vscode = [
  # Language
  "MS-CEINTL.vscode-language-pack-ja",
  # Appearance
  "dracula-theme.theme-dracula",
  "PKief.material-icon-theme",
  # Editor
  "EditorConfig.EditorConfig",
  "asvetliakov.vscode-neovim",
  "christian-kohler.path-intellisense",
  # Environment
  "GitHub.codespaces",
  "ms-azuretools.vscode-docker",
  "ms-vscode-remote.remote-containers",
  "ms-vscode-remote.remote-ssh",
  "ms-vscode-remote.remote-ssh-edit",
  "ms-vscode-remote.remote-wsl",
  "ms-vscode-remote.vscode-remote-extensionpack",
  # Python
  "ms-python.isort",
  "ms-python.python",
  "ms-python.vscode-pylance",
  # Jupyter Notebook
  "ms-toolsai.jupyter",
  "ms-toolsai.jupyter-keymap",
  "ms-toolsai.jupyter-renderers",
  "ms-toolsai.vscode-jupyter-cell-tags",
  "ms-toolsai.vscode-jupyter-slideshow",
  "charliermarsh.ruff",
  # Tools
  "alefragnani.numbered-bookmarks",
  "alefragnani.project-manager",
  "Gruntfuggly.todo-tree",
  "usernamehw.errorlens",
]
