-- -*-mode:lua-*- vim:ft=lua

return {
  {
    type    = "ruby",
    name    = "debug current file",
    bundle  = "",
    request = "attach",
    command = "ruby",
    script  = "${file}",
    server  = "127.0.0.1",
  },
  {
    type    = "ruby",
    name    = "run current test file",
    bundle  = "bundle",
    request = "attach",
    command = "rails test",
    script  = "${file}",
    server  = "127.0.0.1",
  },
  {
    type    = "ruby",
    name    = "run test",
    bundle  = "bundle",
    request = "attach",
    command = "rails test",
    script  = "./test",
    server  = "127.0.0.1",
  },
  {
    type    = "ruby",
    name    = "run rails",
    bundle  = "bundle",
    request = "attach",
    command = "rails",
    script  = "s",
    server  = "127.0.0.1",
    localfs = true,
  },
  {
    type    = "ruby",
    name    = "run current spec file",
    localfs = true,
    request = "attach",
    command = "rspec",
    script  = "${file}",
  },
  {
    type    = "ruby",
    name    = "run rspec",
    bundle  = "bundle",
    request = "attach",
    command = "rspec",
    script  = "./spec",
    server  = "127.0.0.1",
  },
}
