# -*-mode:toml-*- vim:ft=toml

[font.family]
ascii    = "JetBrainsMonoNL NFM"
nonascii = "PlemolJP Console NF"
combined = "UDEV Gothic NFLG"

[font.size]
xlarge = 16
large  = 14
medium = 12
small  = 11
xsmall = 10
