# -*-mode:toml-*- vim:ft=toml

[ghostty]
opacity = 0.8

[ghostty.background]
opacity = 0.4
image   = "daft-punk-music-retro-style-wallpaper.jpg"

[ghostty.theme]
light = "Builtin Solarized Light"
dark  = "GitHub Dark"

[ghostty.cursor]
color = "#ccff00"
text  = "#030303"

[ghostty.selected.normal]
foreground = "#adc7e6"
background = "#24283b"

[ghostty.selected.search]
foreground = "#c0caf5"
background = "#364a82"

[ghostty.shader]
enabled = false
animate = true
module  = "" # Usage: cubes|galaxy|just-snow|sparks-from-fire
