# -*-mode:toml-*- vim:ft=toml

[nushell]
# See usable modules: https://github.com/nushell/nu_scripts/tree/main/custom-completions
completions = [
  "eza", "less", "bat", "btm",
  "curl", "ssh",
  "tar", "make",
  "git", "gh",
  "docker",
  "cargo", "rustup",
  "npm", "pnpm",
  "rg",
  "vscode"
]

# See usable modules: https://github.com/nushell/nu_scripts/tree/main/modules
modules = [ "system", "argx", "history-utils" ]

# See usable themes: https://github.com/nushell/nu_scripts/tree/main/themes/nu-themes
themes  = [ "onedark", "tokyo-night" ]
