# -*-mode:toml-*- vim:ft=toml

[opencode.models]
ultra   = [
  "opencode/qwen-3.6-plus-free",
  "opencode/deepseek-v4-flash-free",
  "opencode/minimax-m2.5-free",
  "opencode/big-pickle",
]
elite   = [
  "opencode/deepseek-v4-flash-free",
  "opencode/mimo-v2.5-free",
  "opencode/minimax-m2.5-free",
  "opencode/nemotron-3-super-free",
  "opencode/big-pickle",
]
general = [
  "opencode/mimo-v2.5-free",
  "opencode/minimax-m2.5-free",
  "opencode/big-pickle",
  "openrouter/nvidia/nemotron-3-super-120b-a12b:free",
  "openrouter/openai/gpt-oss-120b",
]
lite    = [
  "opencode/minimax-m2.5-free",
  "opencode/nemotron-3-super-free",
  "openrouter/nvidia/nemotron-3-super-120b-a12b:free",
]
micro   = [
  "openrouter/z-ai/glm-4.5-air:free",
  "openrouter/nvidia/nemotron-3-super-120b-a12b:free",
  "opencode/nemotron-3-super-free",
]
