# -*-mode:toml-*- vim:ft=toml

opencode.theme = "github"

opencode.providers.enabled = ["opencode", "openrouter", "ollama-cloud"]

[opencode.providers.opencode]
name      = "OpenCode Zen"
npm       = "@ai-sdk/openai-compatible"
whitelist = ["deepseek-v4-flash-free", "mimo-v2.5-free", "nemotron-3-ultra-free", "big-pickle"]

  [opencode.providers.opencode.options]
  baseURL = "https://opencode.ai/zen/v1"
  apiKey  = "{env:OPENCODE_API_KEY}"

  [opencode.providers.opencode.models]
  "deepseek-v4-flash-free" = { name = "DeepSeek V4 Flash" }
  "mimo-v2.5-free"         = { name = "Mimo V2.5" }
  "nemotron-3-ultra-free"  = { name = "NVIDIA Nemotron 3 Ultra" }
  "big-pickle"             = { name = "Big Pickle" }

[opencode.providers.ollama]
name      = "Ollama Cloud"
npm       = "@ai-sdk/openai-compatible"
whitelist = ["glm-5.1:cloud", "kimi-k2.6:cloud", "minimax-m3:cloud", "nemotron-3-ultra:cloud"]

  [opencode.providers.ollama.options]
  baseURL      = "https://ollama.com/v1"
  apiKey       = "{env:OLLAMA_API_KEY}"
  timeout      = 300000
  chunkTimeout = 60000

  [opencode.providers.ollama.models]
  "glm-5.1:cloud"          = { name = "GLM 5.1 (cloud)" }
  "kimi-k2.6:cloud"        = { name = "Kimi k2.6 (cloud)" }
  "minimax-m3:cloud"       = { name = "Minimax-m3 (cloud)" }
  "nemotron-3-ultra:cloud" = { name = "NVIDIA Nemotron 3 Ultra (cloud)" }

[opencode.providers.openrouter]
name      = "OpenRouter"
npm       = "@ai-sdk/openai-compatible"
whitelist = ["moonshotai/kimi-k2.6:free", "nvidia/nemotron-3-ultra-550b-a55b:free", "nvidia/nemotron-3-super-120b-a12b:free"]

  [opencode.providers.openrouter.options]
  baseURL      = "https://openrouter.ai/api/v1"
  apiKey       = "{env:OPENROUTER_API_KEY}"
  timeout      = 300000
  chunkTimeout = 60000

  [opencode.providers.openrouter.models]
  "moonshotai/kimi-k2.6:free"              = { name = "Kimi K2.6" }
  "nvidia/nemotron-3-ultra-550b-a55b:free" = { name = "NVIDIA Nemotron 3 Ultra" }
  "nvidia/nemotron-3-super-120b-a12b:free" = { name = "NVIDIA Nemotron 3 Super" }

[opencode.models]
ultra   = [
  "opencode/minimax-m3-free",
  "ollama-cloud/minimax-m3:cloud",

  "openrouter/moonshotai/kimi-k2.6:free",
  "ollama-cloud/kimi-k2.6:cloud",

  "opencode/qwen-3.6-plus-free",
  "opencode/deepseek-v4-flash-free",
]
elite   = [
  "opencode/qwen-3.6-plus-free",
  "opencode/mimo-v2.5-free",
  "opencode/nemotron-3-ultra-free",
  "openrouter/nvidia/nemotron-3-ultra-550b-a55b:free",
  "ollama-cloud/nemotron-3-ultra:cloud",
]
general = [
  "opencode/mimo-v2.5-free",
  "opencode/deepseek-v4-flash-free",
  "opencode/nemotron-3-ultra-free",
  "openrouter/nvidia/nemotron-3-ultra-550b-a55b:free",
]
lite    = [
  "ollama-cloud/glm-5.1:cloud",
  "opencode/nemotron-3-super-free",
  "openrouter/nvidia/nemotron-3-super-120b-a12b:free",
]
micro   = [
  "opencode/nemotron-3-super-free",
  "openrouter/nvidia/nemotron-3-super-120b-a12b:free",
  "opencode/big-pickle",
]
