# -*-mode:toml-*- vim:ft=toml

[extensions]
vscode = [
  # Language
  "MS-CEINTL.vscode-language-pack-ja",
  # Appearance
  "dracula-theme.theme-dracula",
  "PKief.material-icon-theme",
  # Editor
  "EditorConfig.EditorConfig",
  "codezombiech.gitignore",
  "asvetliakov.vscode-neovim",
  "christian-kohler.path-intellisense",
  ## Tools
  "alefragnani.numbered-bookmarks",
  "alefragnani.project-manager",
  "Gruntfuggly.todo-tree",
  "eamodio.gitlens",
  "usernamehw.errorlens",
  ## AI
  "github.copilot",
  "github.copilot-chat",
  # Environment
  ## GitHub
  "GitHub.codespaces",
  "GitHub.vscode-pull-request-github",
  "github.vscode-github-actions",
  "ms-azuretools.vscode-docker",
  "ms-vscode-remote.remote-containers",
  "ms-vscode-remote.remote-ssh",
  "ms-vscode-remote.remote-ssh-edit",
  "ms-vscode-remote.remote-wsl",
  "ms-vscode-remote.vscode-remote-extensionpack",
  # Markup Languages
  "redhat.vscode-xml",
  "redhat.vscode-yaml",
  "tamasfe.even-better-toml",
  # DAP
  "vadimcn.vscode-lldb",
  # Programming Language
  ## Build
  "twxs.cmake",
  ## Rust
  "rust-lang.rust-analyzer",
  "serayuzgur.crates",
  ## C/C++
  "ms-vscode.cpptools",
  ## Python
  "ms-python.isort",
  "ms-python.python",
  "ms-python.vscode-pylance",
  ### Jupyter Notebook
  "ms-toolsai.jupyter",
  "ms-toolsai.jupyter-keymap",
  "ms-toolsai.jupyter-renderers",
  "ms-toolsai.vscode-jupyter-cell-tags",
  "ms-toolsai.vscode-jupyter-slideshow",
  "charliermarsh.ruff",
  ## JS/TS
  "biomejs.biome",
  ## Tex
  "goessner.mdmath",
  ## Math
  "yfzhao.ultra-math-preview"
]
