# -*-mode:toml-*- vim:ft=toml

[extensions]
vscode = [
  # Language
  "MS-CEINTL.vscode-language-pack-ja",
  # Appearance
  "dracula-theme.theme-dracula",
  "PKief.material-icon-theme",
  # Editor
  "EditorConfig.EditorConfig",
  "codezombiech.gitignore",
  "asvetliakov.vscode-neovim",
  "christian-kohler.path-intellisense",
  ## Tools
  "alefragnani.numbered-bookmarks",
  "alefragnani.project-manager",
  "Gruntfuggly.todo-tree",
  "usernamehw.errorlens",
  ## AI
  "github.copilot",
  "github.copilot-chat",
  "github.copilot-labs",
  # Environment
  ## GitHub
  "GitHub.codespaces",
  "github.vscode-github-actions",
  "ms-azuretools.vscode-docker",
  "ms-vscode-remote.remote-containers",
  "ms-vscode-remote.remote-ssh",
  "ms-vscode-remote.remote-ssh-edit",
  "ms-vscode-remote.remote-wsl",
  "ms-vscode-remote.vscode-remote-extensionpack",
  # XML/YAML
  "redhat.vscode-xml",
  "redhat.vscode-yaml",
  # Python
  "ms-python.isort",
  "ms-python.python",
  "ms-python.vscode-pylance",
  ## Jupyter Notebook
  "ms-toolsai.jupyter",
  "ms-toolsai.jupyter-keymap",
  "ms-toolsai.jupyter-renderers",
  "ms-toolsai.vscode-jupyter-cell-tags",
  "ms-toolsai.vscode-jupyter-slideshow",
  "charliermarsh.ruff",
  # JS/TS
  "biomejs.biome",
]
