[zed.theme]
light = "GitHub Dark"
dark  = "GitHub Dark"
mode  = "system"
icon  = "Material Icon Theme"

[zed.ui]

[zed.terminal]

[zed.search]
smartcase = true

[zed.filetypes]
"Dockerfile" = ["Dockerfile.*"]
"Git Attributes" = ["**/{git,.git,.git/info}/attributes"]
"Git Config" = [ "*.gitconfig", "**/{git,.git/modules,.git/modules/*}/config" ]
"Git Ignore" = ["**/{git,.git}/ignore", "**/.git/info/exclude"]
"env" = [".env", "**/.env*", "**/.envrc*"]
"GitHub Actions" = [ "**/.github/workflows/*.yaml", "**/.github/workflows/*.yml" ]

[zed.lsp.diagnostics]

[zed.lsp.inlay_hints]

[zed.lsp.servers.texlab]

[zed.extensions]
# Appearance
material-icon-theme = true
github-theme        = true

# Language support
editorconfig   = true
dockerfile     = true
docker-compose = true
gosum          = true
gotmpl         = true
fish           = true
lua            = true
sql            = true
toml           = true
xml            = true
ini            = true
csv            = true
rainbow-csv    = true
latex          = true
