# -*-mode:toml-*- vim:ft=toml

[zellij.colors]
fg      = "#a0a8b7"
bg      = "#282c34"
black   = "#0e1013"
grey    = "#535965"
white   = "#f0f0f0"
red     = "#e55561"
crimson = "#be5046"
pink    = "#ff79c6"
olive   = "#98c379"
moss    = "#b1f2a7"
beryl   = "#56b6c2"
azure   = "#61afef"
navy    = "#21252b"
brown   = "#d19a66"
orange  = "#cc9057"
yellow  = "#e2b86b"
green   = "#8ebd6b"
blue    = "#4fa6ed"
cyan    = "#48b0bd"
purple  = "#bf68d9"
magenta = "#a626a4"
