###############################################################
# This configuration file lets you
# - define new commands
# - change the shortcut or triggering keys of built-in verbs
# - change the colors
# - set default values for flags
#
# Configuration documentation is available at
#     https://dystroy.org/broot
###############################################################

###############################################################
# Default flags
# You can set up flags you want broot to start with by
# default, for example `default_flags="ihp"` if you usually want
# to see hidden and gitignored files and the permissions (then
# if you don't want the hidden files you can launch `br -H`)
# A popular flag is the `g` one which displays git related info.
#
# show hidden files and git status
default_flags = "gh"
# show a triangle indicator on the current line
show_selection_mark = true
# use 24bit color always
true_colors = true
# quit with esc at the top level
quit_on_last_cancel = true

icon_theme = "vscode"

syntax_theme = "InspiredGitHub"

###############################################################
# Imports
#
# While it's possible to have all configuration in one file,
# it's more convenient to split it in several ones.
# Importing also allows to set a condition on the terminal's
# color, which makes it possible to have a different skin
# chosen when your terminal has a light background and when
# it has a light one.
[[imports]]
# Verbs are better configured in verbs.hjson. But you
# can also add another files for your personal verbs
file = "verbs.toml"

# This file contains the skin to use when the terminal
# is dark (or when this couldn't be determined)
[[imports]]
luma= [ "dark", "unknown" ]
# (un)comment to choose your preferred skin
# file = "skins/dark-blue.hjson"
# file = "skins/dark-gruvbox.hjson"
# file = "skins/dark-orange.hjson"
file = "skins/solarized-dark.hjson"

# This skin is imported when your terminal is light
[[imports]]
luma = "light"
# (un)comment to choose your preferred skin
file = "skins/solarized-light.hjson"
# file = "skins/white.hjson"

[[imports]]
file = "ext_colors.toml"
