[ext_colors]
# Media
## Image
png   = "rgb(255, 156, 75)"
jpg   = "rgb(255, 156, 75)"
gif   = "rgb(255, 156, 75)"
svg   = "rgb(253, 135, 0)"
## Audio
wav  = "yellow"
flac = "yellow"
alac = "yellow"
aiff = "yellow"
mp3  = "yellow"
m4a  = "yellow"
## Video
mp4  = "green"
mkv  = "green"
# Programming Language
# color from https://github.com/ozh/github-colors
c       = "rgb(67,  67,  67)"
h       = "rgb(67,  67,  67)"
cpp     = "rgb(237, 48,  107)"
hpp     = "rgb(237, 48,  107)"
m       = "rgb(50,  111, 236)"
mm      = "rgb(85,  74,  251)"
swift   = "rgb(235, 57,  44)"
cuda    = "rgb(46,  22,  44)"
metal   = "rgb(122, 0,   228)"
glsl    = "rgb(69,  115, 148)"
hlsl    = "rgb(155, 199, 78)"
wasm    = "rgb(4,   14,  46)"
zig     = "rgb(229, 125, 74)"
rs      = "rgb(214, 147, 114)"
go      = "rgb(20,  157, 207)"
java    = "rgb(158, 94,  20)"
class   = "rgb(255, 128, 75)"
scala   = "rgb(174, 25,  49)"
kotlin  = "rgb(152, 95,  255)"
erlang  = "rgb(168, 32,  134)"
elixir  = "rgb(88,  53,  104)"
haskell = "rgb(75,  60,  115)"
py      = "rgb(42,  94,  149)"
ipynb   = "rgb(207, 70,  14)"
rb      = "rgb(91,  12,  17)"
pl      = "rgb(18,  130, 180)"
php     = "rgb(61,  73,  130)"
sh      = "rgb(123, 222, 64)"
fish    = "rgb(61,  163, 55)"
ps1     = "rgb(1,   25,  69)"
lua     = "rgb(0,   0,   108)"
vim     = "rgb(28,  144, 59)"
js      = "rgb(237, 220, 73)"
jsx     = "rgb(237, 220, 73)"
ts      = "rgb(39,  97,  184)"
tsx     = "rgb(39,  98,  186)"
vue     = "rgb(55,  173, 113)"
json    = "rgb(31,  31,  31)"
json5   = "rgb(31,  101, 168)"
jsonc   = "rgb(31,  31,  31)"
yml     = "rgb(189, 0,   24)"
toml    = "rgb(137, 48,  27)"
xml     = "rgb(9,   74,  154)"
html    = "rgb(219, 53,  31)"
hxml    = "rgb(241, 115, 19)"
css     = "rgb(67,  43,  103)"
scss    = "rgb(183, 59,  121)"
sql     = "rgb(219, 122, 7)"
csv     = "rgb(30,  68,  55)"
tsv     = "rgb(30,  68,  55)"
md      = "rgb(10,  42,  145)"
# Archive
zip   = "blue"
jar   = "blue"
tar   = "blue"
gz    = "blue"
xz    = "blue"
gzip  = "blue"
