# -*-mode:toml-*- vim:ft=toml

[default]
default.locale = "en_us"

[default.extend-words]
iterm = "iterm"
noice = "noice"

fo = "fo"
nd = "nd"
ot = "ot"

[files]
extend-exclude = [
  ".git/", ".github/",
  ".typos.toml", "_typos.toml",
  "node_modules", "*lock.json", "*.lock", "*.json", "pnpm-lock.yaml",
  "*.min.js", "*.js",
  "*.min.css", "*.css",
  "Gemfile.lock", "vendor/**/*",
  "go.mod", "go.sum",
  "*.plist", "*.pbxproj", "*.xcscheme", "*.xcresult",
  "*.xccolortheme", "*.xib", "*.storyboard",
  "*.svg", "*.png",
]
