# -*-mode:toml-*- vim:ft=toml

[default]
default.locale = "en_us"
check-filename = true
check-file     = true
unicode        = true
ignore-hex     = true
identifier-leading-digits = false
extend-ignore-re = [
  "(?Rm)^.*(<!--|#|//)\\s*spellchecker:disable-line(-->|\n)?$",
  "(?s)(<!--|#|//)\\s*spellchecker:off\\s*(-->|\n).*?(<!--|#|//)\\s*spellchecker:on",
  "(?s)```.*?``` ",              # multi-line code block
  "(?s)```[a-zA-Z0-9]*\n.*?```", # multi-line code block
  "(?s)`.*?` ",                  # inline code block
]

[default.extend-words]
iterm = "iterm"
noice = "noice"

fo = "fo"
nd = "nd"
ot = "ot"

[files]
ignore-hidden = true
ignore-files  = true
ignore-dot    = true
ignore-vcs    = true
ignore-global = true
ignore-parent = true

extend-exclude = [
  ".git/", ".github/",
  ".typos.toml", "_typos.toml",
  "node_modules/**", "*lock.json", "*.lock", "*.json", "pnpm-lock.yaml",
  "*.min.js", "*.js", "*.min.css", "*.css", "*.map"
  "Gemfile.lock", "vendor/**/*",
  "go.mod", "go.sum",
  # Xcode
  "*.pbxproj", "xcscheme", "*.xcresult", "*.xccolortheme", "*.xib", "*.nib", "*.storyboard",
  "*.svg", "*.png", "*.drawio",
  "CHANGELOG.md",
]
