# -*-mode:toml-*- vim:ft=toml

[default]
default.locale = "en_us"

[default.extend-words]
iterm = "iterm"
noice = "noice"

fo = "fo"
nd = "nd"
ot = "ot"

[files]
ignore-hidden = true
ignore-files  = true
ignore-dot    = true
ignore-vcs    = true
ignore-global = true
ignore-parent = true

extend-exclude = [
  ".git/", ".github/",
  ".typos.toml", "_typos.toml",
  "node_modules/**", "*lock.json", "*.lock", "*.json", "pnpm-lock.yaml",
  "*.min.js", "*.js", "*.min.css", "*.css", "*.map"
  "Gemfile.lock", "vendor/**/*",
  "go.mod", "go.sum",
  # Xcode
  "*.pbxproj", "xcscheme", "*.xcresult", "*.xccolortheme", "*.xib", "*.nib", "*.storyboard",
  "*.svg", "*.png", "*.drawio",
  "CHANGELOG.md",
]
