[flags]
basic = false
rate  = 500
hide_time = false

# CPU
current_usage = true
hide_avg_cpu = false

# Process
group_processes = false

# Memory
mem_as_value = true
enable_gpu_memory = true

# Search
case_sensitive = false
regex = false

# Graph
dot_marker = false
hide_table_gap = true

# layouts
[[row]]
  ratio = 3
  [[row.child]]
  ratio = 4
  type  = "cpu"
  [[row.child]]
  ratio = 3
  type  = "mem"
  [[row.child]]
  ratio = 2
  type  = "battery"
[[row]]
  ratio = 3
  [[row.child]]
  ratio = 4
  type  = "disk"
  [[row.child]]
  ratio = 3
  type  = "net"
  [[row.child]]
  ratio = 2
  type  = "temp"
[[row]]
  ratio = 4
  [[row.child]]
  type  = "proc"
  default=true

[colors]
graph_color  = "Gray"

# Border
border_color = "White"
highlighted_border_color = "LightMagenta"
table_header_color = "Blue"

# Text
text_color = "White"
selected_text_color = "Black"

# Title
widget_title_color = "Cyan"
selected_bg_color = "Magenta"

# CPU
avg_cpu_color = "Red"
cpu_core_colors = [ "#e78284", "#ef9f76", "#e5c890", "#a6d189", "#85c1dc", "#ca9ee6" ]
gpu_core_colors = [ "#74c7ec", "#cba6f7", "#f38ba8", "#fab387", "#f9e2af", "#a6e3a1" ]
