[flags]
basic     = false
rate      = 500
hide_time = false

# CPU / GPU
current_usage = true
enable_gpu    = true

# Process
group_processes = false

# Memory
process_memory_as_value = true

# Graph
dot_marker     = false
hide_table_gap = true

[cpu]
hide_avg_cpu = false

[processes]
default_grouped = false
case_sensitive  = false
regex           = false

# layouts
[[row]]
ratio = 3

  [[row.child]]
  ratio = 4
  type  = "cpu"

  [[row.child]]
  ratio = 3
  type  = "mem"

  [[row.child]]
  ratio = 2
  type  = "battery"

[[row]]
ratio = 3

  [[row.child]]
  ratio = 4
  type  = "disk"

  [[row.child]]
  ratio = 3
  type  = "net"

  [[row.child]]
  ratio = 2
  type  = "temp"

[[row]]
ratio = 4

  [[row.child]]
  type    = "proc"
  default = true

[styles]
theme = "default"
