---
name: lint

on:
  pull_request:
    branches:
      - main

jobs:
  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Run shellcheck
      uses: azohra/shell-linter@master
      env:
        SHELLCHECK_OPTS: -P **/*.sh
