---
name: lint

on:
  push:
    branches:
      - main
    paths:
      - '**.sh'

jobs:
  shellcheck:
    name: 'ShellCheck'
    runs-on: macos-12
    steps:
    - uses: 'actions/checkout@v3'
    - name: 'Run shellcheck'
      uses: 'azohra/shell-linter@master'
      with:
        path: '*.sh'
      env:
        SHELLCHECK_OPTS: '-x'
